name: EasyTier Docker

on:
  workflow_dispatch:  # 保留手动触发，但不再定义 inputs

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # run_id 固定写死或直接去掉，看你是否还需要下载 EasyTier-Core 的产物
          run_id: 10228239965
          repo: EasyTier/EasyTier
          path: docker_context

      - name: List files
        run: |
          ls -l -R .

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker_context
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/riscv64
          push: true
          file: .github/workflows/Dockerfile
          # 这里直接写死 tag，不再依赖 inputs
          tags: |
            easytier/easytier:v2.4.5
            easytier/easytier:latest
            ghcr.io/easytier/easytier:v2.4.5
            ghcr.io/easytier/easytier:latest
